# HJ100 等差数列

### 描述
等差数列 2，5，8，11，14。。。。
（从 2 开始的 3 为公差的等差数列）
输出求等差数列前n项和


### 数据范围： 
1
≤
n
≤
1000
 
1≤n≤1000 
### 输入描述：
输入一个正整数n。

### 输出描述：
输出一个相加后的整数。

### 示例1

输入：
2

输出：
7

说明：
2+5=7

In [ ]:
n = int(input())

lst = []

for i in range(n):
    lst.append(2+3*i)

print(sum(lst))

---

# HJ101 输入整型数组和排序标识，对其元素按照升序或降序进行排序

描述   
输入整型数组和排序标识，对其元素按照升序或降序进行排序   

数据范围： 
1
≤
n
≤
1000
 
1≤n≤1000  ，元素大小满足 
0
≤
v
a
l
≤
100000
 
0≤val≤100000 
输入描述：
第一行输入数组元素个数
第二行输入待排序的数组，每个数用空格隔开
第三行输入一个整数0或1。0代表升序排序，1代表降序排序

输出描述：
输出排好序的数字

示例1

输入：
8   

1 2 4 9 3 55 64 25

0

输出：
1 2 3 4 9 25 55 64

输入：

5

1 2 3 4 5

1

输出：

5 4 3 2 1

In [23]:
n = int(input())
#lst = []

'''
for i in range(n):
    lst.append(input())
'''
lst = input().split(' ')

p = int(input())

202
566 55461 34431 13321 12965 21890 59745 28165 20281 13499 27982 77285 75626 29072 38901 19612 26742 22419 9270 30476 94647 75337 74267 33862 34987 46545 9591 463 24660 47957 86031 68843 5890 26992 35688 72392 80521 76905 37697 23994 62653 57991 4949 7951 10097 71456 3545 26822 47859 22119 52714 25920 24886 3602 26034 9719 84715 76802 65424 63990 90460 39126 4327 17564 18574 15832 65179 68451 1615 12917 2639 27312 79236 95826 36984 76194 83789 48869 33343 89537 9737 6503 55819 73571 43546 30342 26367 21262 47133 78945 35732 93908 24265 51367 67012 50418 94517 51002 10589 63694 76680 6805 48049 22914 52788 83657 82447 15101 78550 13977 4469 82037 35391 15845 80503 72998 24779 9460 67514 61189 84581 67966 67412 4586 87998 82798 33861 59078 92604 54600 43855 39018 7861 28237 54370 1892 21123 16942 64835 9832 85132 47867 32163 39919 81639 9003 86584 36367 77058 38903 24330 44348 88717 73941 62422 85605 17297 36119 72523 11411 56621 52471 85575 86821 68452 4279 28229 40806 66387 38165 51853 85033 68269 78841 7238 11004 36235 90312 20842 79829 30427 73024 62938 27266 62212 70054 25830 22305 94602 73078 82674 11809 21868 80558 18143 9505 90486 77343 59449 57464 58010 1555
1

In [15]:
n = 202

lst = '566 55461 34431 13321 12965 21890 59745 28165 20281 13499 27982 77285 75626 29072 38901 19612 26742 22419 9270 30476 94647 75337 74267 33862 34987 46545 9591 463 24660 47957 86031 68843 5890 26992 35688 72392 80521 76905 37697 23994 62653 57991 4949 7951 10097 71456 3545 26822 47859 22119 52714 25920 24886 3602 26034 9719 84715 76802 65424 63990 90460 39126 4327 17564 18574 15832 65179 68451 1615 12917 2639 27312 79236 95826 36984 76194 83789 48869 33343 89537 9737 6503 55819 73571 43546 30342 26367 21262 47133 78945 35732 93908 24265 51367 67012 50418 94517 51002 10589 63694 76680 6805 48049 22914 52788 83657 82447 15101 78550 13977 4469 82037 35391 15845 80503 72998 24779 9460 67514 61189 84581 67966 67412 4586 87998 82798 33861 59078 92604 54600 43855 39018 7861 28237 54370 1892 21123 16942 64835 9832 85132 47867 32163 39919 81639 9003 86584 36367 77058 38903 24330 44348 88717 73941 62422 85605 17297 36119 72523 11411 56621 52471 85575 86821 68452 4279 28229 40806 66387 38165 51853 85033 68269 78841 7238 11004 36235 90312 20842 79829 30427 73024 62938 27266 62212 70054 25830 22305 94602 73078 82674 11809 21868 80558 18143 9505 90486 77343 59449 57464 58010 1555'.split(' ')

p = 1

In [24]:
int_lst=[]

for i in lst:
    int_lst.append(int(i))

n_lst = sorted(int_lst)

print(n_lst)
print(p,type(p))

[463, 566, 1555, 1615, 1892, 2639, 3545, 3602, 4279, 4327, 4469, 4586, 4949, 5890, 6503, 6805, 7238, 7861, 7951, 9003, 9270, 9460, 9505, 9591, 9719, 9737, 9832, 10097, 10589, 11004, 11411, 11809, 12917, 12965, 13321, 13499, 13977, 15101, 15832, 15845, 16942, 17297, 17564, 18143, 18574, 19612, 20281, 20842, 21123, 21262, 21868, 21890, 22119, 22305, 22419, 22914, 23994, 24265, 24330, 24660, 24779, 24886, 25830, 25920, 26034, 26367, 26742, 26822, 26992, 27266, 27312, 27982, 28165, 28229, 28237, 29072, 30342, 30427, 30476, 32163, 33343, 33861, 33862, 34431, 34987, 35391, 35688, 35732, 36119, 36235, 36367, 36984, 37697, 38165, 38901, 38903, 39018, 39126, 39919, 40806, 43546, 43855, 44348, 46545, 47133, 47859, 47867, 47957, 48049, 48869, 50418, 51002, 51367, 51853, 52471, 52714, 52788, 54370, 54600, 55461, 55819, 56621, 57464, 57991, 58010, 59078, 59449, 59745, 61189, 62212, 62422, 62653, 62938, 63694, 63990, 64835, 65179, 65424, 66387, 67012, 67412, 67514, 67966, 68269, 68451, 68452, 68843, 70054, 71456, 72392, 72523, 72998, 73024, 73078, 73571, 73941, 74267, 75337, 75626, 76194, 76680, 76802, 76905, 77058, 77285, 77343, 78550, 78841, 78945, 79236, 79829, 80503, 80521, 80558, 81639, 82037, 82447, 82674, 82798, 83657, 83789, 84581, 84715, 85033, 85132, 85575, 85605, 86031, 86584, 86821, 87998, 88717, 89537, 90312, 90460, 90486, 92604, 93908, 94517, 94602, 94647, 95826]
1 <class 'int'>

In [25]:
n_lst2 = []
if p == 1:
    n_lst2 = n_lst[::-1]
    #for i in range(len(n_lst)):
       # n_lst2
else:
    n_lst2 = n_lst
    
print(n_lst2)

for i in n_lst2:
    print(i,end = ' ')

[95826, 94647, 94602, 94517, 93908, 92604, 90486, 90460, 90312, 89537, 88717, 87998, 86821, 86584, 86031, 85605, 85575, 85132, 85033, 84715, 84581, 83789, 83657, 82798, 82674, 82447, 82037, 81639, 80558, 80521, 80503, 79829, 79236, 78945, 78841, 78550, 77343, 77285, 77058, 76905, 76802, 76680, 76194, 75626, 75337, 74267, 73941, 73571, 73078, 73024, 72998, 72523, 72392, 71456, 70054, 68843, 68452, 68451, 68269, 67966, 67514, 67412, 67012, 66387, 65424, 65179, 64835, 63990, 63694, 62938, 62653, 62422, 62212, 61189, 59745, 59449, 59078, 58010, 57991, 57464, 56621, 55819, 55461, 54600, 54370, 52788, 52714, 52471, 51853, 51367, 51002, 50418, 48869, 48049, 47957, 47867, 47859, 47133, 46545, 44348, 43855, 43546, 40806, 39919, 39126, 39018, 38903, 38901, 38165, 37697, 36984, 36367, 36235, 36119, 35732, 35688, 35391, 34987, 34431, 33862, 33861, 33343, 32163, 30476, 30427, 30342, 29072, 28237, 28229, 28165, 27982, 27312, 27266, 26992, 26822, 26742, 26367, 26034, 25920, 25830, 24886, 24779, 24660, 24330, 24265, 23994, 22914, 22419, 22305, 22119, 21890, 21868, 21262, 21123, 20842, 20281, 19612, 18574, 18143, 17564, 17297, 16942, 15845, 15832, 15101, 13977, 13499, 13321, 12965, 12917, 11809, 11411, 11004, 10589, 10097, 9832, 9737, 9719, 9591, 9505, 9460, 9270, 9003, 7951, 7861, 7238, 6805, 6503, 5890, 4949, 4586, 4469, 4327, 4279, 3602, 3545, 2639, 1892, 1615, 1555, 566, 463]
95826 94647 94602 94517 93908 92604 90486 90460 90312 89537 88717 87998 86821 86584 86031 85605 85575 85132 85033 84715 84581 83789 83657 82798 82674 82447 82037 81639 80558 80521 80503 79829 79236 78945 78841 78550 77343 77285 77058 76905 76802 76680 76194 75626 75337 74267 73941 73571 73078 73024 72998 72523 72392 71456 70054 68843 68452 68451 68269 67966 67514 67412 67012 66387 65424 65179 64835 63990 63694 62938 62653 62422 62212 61189 59745 59449 59078 58010 57991 57464 56621 55819 55461 54600 54370 52788 52714 52471 51853 51367 51002 50418 48869 48049 47957 47867 47859 47133 46545 44348 43855 43546 40806 39919 39126 39018 38903 38901 38165 37697 36984 36367 36235 36119 35732 35688 35391 34987 34431 33862 33861 33343 32163 30476 30427 30342 29072 28237 28229 28165 27982 27312 27266 26992 26822 26742 26367 26034 25920 25830 24886 24779 24660 24330 24265 23994 22914 22419 22305 22119 21890 21868 21262 21123 20842 20281 19612 18574 18143 17564 17297 16942 15845 15832 15101 13977 13499 13321 12965 12917 11809 11411 11004 10589 10097 9832 9737 9719 9591 9505 9460 9270 9003 7951 7861 7238 6805 6503 5890 4949 4586 4469 4327 4279 3602 3545 2639 1892 1615 1555 566 463

# 注意此处 p的值，输入的是'1'，而判断p == 1的话，是错的

---